# Generated by Django 5.0.3 on 2024-03-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_removed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_stored',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fragile',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_class',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_num',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_store',
        ),
        migrations.RemoveField(
            model_name='item',
            name='units',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.AddField(
            model_name='item',
            name='cpu',
            field=models.CharField(max_length=100, null=True, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='item',
            name='gpu',
            field=models.CharField(max_length=100, null=True, verbose_name='GPU'),
        ),
        migrations.AddField(
            model_name='item',
            name='ram',
            field=models.CharField(max_length=100, null=True, verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial',
            field=models.CharField(max_length=100, null=True, verbose_name='Device Serial'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Device name'),
        ),
    ]
